Select annotation
PDFTron/pdftron-react-native pull request #132
Opened 2020-09-01 23:07 UTC by Maxwell-Yang-PDFTron

2020-09-02 19:09 UTC, sgong-pdftron commented
Android side OK

2020-09-02 19:10 UTC, sgong-pdftron approved these changes

2020-09-03 15:09 UTC, sgong-pdftron requested changes
Readme for this PR and https://github.com/PDFTron/pdftron-react-native/pull/133 required

2020-09-03 15:11 UTC, sgong-pdftron approved these changes
I see it was added to the other PR, discard previous message

2020-09-03 16:15 UTC, JamesTron approved these changes

2020-09-03 16:25 UTC, merged