Implement setFlagForAnnotations
PDFTron/pdftron-react-native pull request #134
Opened 2020-09-01 23:26 UTC by Maxwell-Yang-PDFTron

2020-09-02 00:02 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +                    [annot SetFlag:annotFlag value:flagValue];
This line appears to be an issue, where `flagValue` is an NSNumber object, but the method is expecting a BOOL. If you change it to `[flagValue boolValue]`, it should work.

2020-09-02 19:29 UTC, sgong-pdftron requested changes
Missing enum in Config.js, see `FieldFlags` for example

2020-09-02 19:30 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +                        case "hidden":
constant out in static final variable

2020-09-02 22:14 UTC, sgong-pdftron requested changes

2020-09-02 22:14 UTC, sgong-pdftron commented on ios/RNTPTDocumentView.m
> +                } else if ([flag isEqualToString:@"locked_contents"]) {
update the strings to match config strings

2020-09-03 15:14 UTC, sgong-pdftron commented on README.md
> +pageNumber | int | the page number where the targe annotation is located
mention page is 1-indexed

2020-09-03 15:19 UTC, sgong-pdftron requested changes

2020-09-03 15:19 UTC, sgong-pdftron commented on README.md
> +bool, optional, default to false If true, annotation created by user A cannot be modified by user B, else anyone can modify any annotation.
if true should go new line, you can click on your branch on github to check how it looks

2020-09-03 15:19 UTC, sgong-pdftron commented on README.md
> +bool, optional, default to false If true, annotation created by user A cannot be modified by user B, else anyone can modify any annotation.
change to 

If true, annotation's flags will be taken into account when it is selected, for example, a locked annotation can not be resized or moved.

2020-09-03 15:40 UTC, sgong-pdftron requested changes

2020-09-03 15:40 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +                    annot.setFlag(flagVal, flagValue);
call pdfviewctrl.update(annot, page) to update in the viewer

2020-09-03 15:41 UTC, sgong-pdftron commented on README.md
> +bool, optional, default to false If true, annotation created by user A cannot be modified by user B, else anyone can modify any annotation.
yes fix all, if true should always be on new line

2020-09-03 16:14 UTC, sgong-pdftron approved these changes

2020-09-03 16:14 UTC, sgong-pdftron commented
Android OK

2020-09-03 16:20 UTC, JamesTron requested changes

2020-09-03 16:20 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +        shouldUnlock = YES;
This way of locking is correct, but it's the "old way" of doing it, and we're not writing new code like this anymore. We have a couple of convenience methods that make this easier to write here (one that acquires a read lock and one that acquires a write lock): https://www.pdftron.com/api/ios/Classes/PTPDFViewCtrl.html#/Locking

You can see an example of its usage in the `deleteAnnotations:` method in this file. Could you please change any new code you've written to use the block-based locking? Thank you!

2020-09-03 19:02 UTC, JamesTron approved these changes
Looks good 👍

2020-09-03 19:26 UTC, merged