Implement get-document-path
PDFTron/pdftron-react-native pull request #145
Opened 2020-10-09 17:25 UTC by Maxwell-Yang-PDFTron

2020-10-09 19:55 UTC, sgong-pdftron commented on README.md
> +  console.log('The path to current document is: ', path);
this._viewer.getDocumentPath((path) => {
        console.log('The path to current document is: ', path);
      });

2020-10-09 20:21 UTC, sgong-pdftron requested changes

2020-10-09 20:21 UTC, sgong-pdftron commented on README.md
> +  console.log('The path to current document is: ', path);
and it doesnt seem to be working for me for some reason when i tried as is... not too sure why, could you check again?

2020-10-14 16:49 UTC, sgong-pdftron approved these changes

2020-10-14 23:46 UTC, JamesTron approved these changes

2020-10-15 15:29 UTC, merged