thumbnail filter mode
PDFTron/pdftron-react-native pull request #176
Opened 2020-11-26 23:43 UTC by Maxwell-Yang-PDFTron

2020-11-27 21:26 UTC, sgong-pdftron requested changes

2020-11-27 21:26 UTC, sgong-pdftron commented on README.md
> +Defines filter modes that should be hidden on thumbnail view
in the thumbnails browser

2020-11-30 15:48 UTC, sgong-pdftron approved these changes

2020-12-01 16:35 UTC, JamesTron approved these changes

2020-12-01 16:38 UTC, merged