get annotation(s)
PDFTron/pdftron-react-native pull request #246
Opened 2021-03-31 21:18 UTC by Maxwell-Yang-PDFTron

Functions:
getAnnotationAtPoint
getAnnotationsAtLine
getAnnotationsOnPage

2021-04-01 22:43 UTC, JamesTron requested changes

2021-04-01 22:43 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +                annotation = [self getAnnotationData:annot pageNumber:[[annot GetPage] GetIndex] pdfViewCtrl:pdfViewCtrl];
`[annot GetPage]` is not reliable and should not be used. Instead, you should use https://www.pdftron.com/api/ios/Classes/PTPDFViewCtrl.html#/c:objc(cs)PTPDFViewCtrl(im)GetPageNumberFromScreenPt:y: to get the page number. (and use https://www.pdftron.com/api/ios/Classes/PTPDFDoc.html#/c:objc(cs)PTPDFDoc(im)GetPage: if you ever need the page object.)

2021-04-01 22:43 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +                    [annotations addObject:[self getAnnotationData:annot pageNumber:[[annot GetPage] GetIndex] pdfViewCtrl:pdfViewCtrl]];
Do not use `[annot GetPage]` as explained above.

2021-04-01 22:43 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +                    [annotations addObject:[self getAnnotationData:annot pageNumber:[[annot GetPage] GetIndex] pdfViewCtrl:pdfViewCtrl]];
Do not use `[annot GetPage]` as explained above.

2021-04-05 15:49 UTC, sgong-pdftron requested changes

2021-04-05 15:49 UTC, sgong-pdftron commented on API.md
> +#### getAnnotationsAtLine
bad API name, it should be getAnnotationAt (one) and getAnnotationListAt (multiple), it could be a line, a rect etc.

2021-04-05 16:00 UTC, sgong-pdftron requested changes

2021-04-05 16:00 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +                    annotation = getAnnotationData(annot, annot.getPage().getIndex());
never use getPage, see James comment for this, apply to all usage of getPage

2021-04-07 18:55 UTC, sgong-pdftron approved these changes

2021-04-08 00:35 UTC, JamesTron approved these changes

2021-04-08 01:37 UTC, merged