Expose native UI customization apis
PDFTron/pdftron-react-native pull request #279
Opened 2021-05-27 00:40 UTC by akwanpdf

Draft exposure of:
- annotationsListEditingEnabled (Android) and PTAnnotationViewController.readonly (iOS)
- imageInReflowEnabled (Android) and PTReflowViewController.reflowMode (iOS)
- reflowOrientation (Android) and PTReflowViewController.scrollingDirection (iOS)

For each property in RN, I used the Android name.

Currently trying to test iOS reflowOrientation implementation but it is getting overridden by whatever the user selects in "View Settings" -> "Vertical Scrolling" inside the emulator app.

2021-05-28 19:15 UTC, sgong-pdftron requested changes
- [x] missing API readme

2021-05-28 19:15 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +        int orientation = ReflowControl.HORIZONTAL;
simplify

2021-06-16 21:16 UTC, sgong-pdftron approved these changes

2021-06-18 21:37 UTC, JamesTron approved these changes

2021-06-18 21:55 UTC, merged