getPropertiesForAnnotation
PDFTron/pdftron-react-native pull request #291
Opened 2021-06-16 21:33 UTC by akwanpdf

getPropertiesForAnnotation retrieves an annotation's properties, excluding customData.

2021-06-16 21:47 UTC, sgong-pdftron commented on API.md
> +    console.log('Properties for annotation: ', JSON.stringify(properties));
stringify is not needed here because it will just print out as a json

2021-06-16 22:22 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
> +    public ReadableMap getPropertiesForAnnotation(int tag, String annotId, int pageNumber) throws PDFNetException {
WritableMap?

2021-06-16 22:22 UTC, sgong-pdftron requested changes

2021-06-16 22:22 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
> +                    ReadableMap propertyMap = mDocumentViewInstance.getPropertiesForAnnotation(tag, annotId, pageNumber);
WritableMap?

2021-06-17 15:19 UTC, sgong-pdftron approved these changes

2021-06-17 22:09 UTC, JamesTron requested changes
No need to re-review after change is made.

2021-06-17 22:09 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +    return map;
```suggestion
    return [map copy[;
```

2021-06-17 22:09 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +    return map;
Returns an immutable copy.

2021-06-17 22:14 UTC, merged