Update Usage section of  README.md
PDFTron/pdftron-react-native pull request #296
Opened 2021-06-23 18:08 UTC by dcupidon

Updated this section to include instructions on how to use local files

2021-06-23 18:10 UTC, sgong-pdftron approved these changes

2021-06-23 21:07 UTC, JamesTron requested changes
Please leave short comments in code saying why/what the commented out section does.

2021-06-25 21:37 UTC, JamesTron commented on README.md
> +  // Uses the platform to determine if storagge permissions need to be requested.
```suggestion
  // Uses the platform to determine if storage permissions need to be requested.
```

2021-06-25 21:37 UTC, JamesTron approved these changes

2021-06-26 00:17 UTC, merged