Undo/Redo State APIs
PDFTron/pdftron-react-native pull request #302
Opened 2021-06-29 18:24 UTC by dcupidon

Exposed APIs to:
* Detect changes in the undo/redo stack's state
* Tell whether an undo/a redo operation can be performed on the current document

2021-06-30 15:06 UTC, sgong-pdftron requested changes

2021-06-30 15:06 UTC, sgong-pdftron commented
- [ ] resolve conflicts

2021-06-30 16:09 UTC, sgong-pdftron approved these changes

2021-07-07 23:31 UTC, dluco reviewed
Just a little type-name change, otherwise looks great!

2021-07-07 23:31 UTC, dluco commented on ios/RNTPTDocumentView.m
> +    PTUndoRedoManager *undoManager = toolManager.undoManager;
Should be the `NSUndoManager` type - the `undoRedoManager` is the `PTUndoRedoManager` (very similar names)
```suggestion
    NSUndoManager *undoManager = toolManager.undoManager;
```

2021-07-07 23:31 UTC, dluco commented on ios/RNTPTDocumentView.m
> +    PTUndoRedoManager *undoManager = toolManager.undoManager;
Same as above

2021-07-08 18:12 UTC, JamesTron approved these changes

2021-07-09 00:55 UTC, merged