Open List Container
PDFTron/pdftron-react-native pull request #329
Opened 2021-07-15 00:17 UTC by dcupidon

Exposed two APIs, one will open the bookmark list and the other will open the outline list. Both are done at the user's request.

2021-07-16 17:20 UTC, sgong-pdftron requested changes

2021-07-16 17:20 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +        if (isPdfLayersListVisible) {
- [ ] null check for pdfviewctrl
- [ ] no need to check visible, the only reason the other ones need to check visible is because it uses index

2021-07-19 20:24 UTC, dluco approved these changes

2021-08-09 19:12 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
> +    public void openLayersList(final int tag, final Promise promise) {
layer is not listed in the APIs

2021-08-09 19:14 UTC, sgong-pdftron requested changes

2021-08-09 19:14 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
> +            documentView.openLists();
- [ ] open navigation lists

2021-08-09 23:19 UTC, dcupidon commented on android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
> +    public void openLayersList(final int tag, final Promise promise) {
Fixed

2021-08-09 23:45 UTC, JamieDass commented on ios/RNTPTDocumentView.m
> +        PTNavigationListsViewController *navigationListsViewController = self.documentViewController.navigationListsViewController;
```suggestion
        PTNavigationListsViewController *navigationListsViewController = self.currentDocumentViewController.navigationListsViewController;
```

2021-08-09 23:46 UTC, JamieDass commented on ios/RNTPTDocumentView.m
> +
```suggestion
-(void)openBookmarkList
{
    if (!self.currentDocumentViewController.bookmarkListHidden) {
        PTNavigationListsViewController *navigationListsViewController = self.currentDocumentViewController..navigationListsViewController;
        navigationListsViewController.selectedViewController = navigationListsViewController.bookmarkViewController;
        [self.currentDocumentViewController. presentViewController:navigationListsViewController animated:YES completion:nil];
    }
}

```

2021-08-09 23:46 UTC, JamieDass commented on ios/RNTPTDocumentView.m
> +
@dcupidon does this fix things for the tabbed viewer?

2021-08-11 19:26 UTC, dluco approved these changes

2021-08-11 20:43 UTC, merged