Expose isReflowMode
PDFTron/pdftron-react-native pull request #330
Opened 2021-07-15 01:03 UTC by akwanpdf

Exposed `isReflowMode` for iOS and Android.

`isReflowMode` method returns whether the viewer is currently in reflow mode.

2021-07-19 20:25 UTC, dluco approved these changes

2021-08-09 19:11 UTC, sgong-pdftron requested changes

2021-08-09 19:11 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +        if (mPdfViewCtrlTabHostFragment != null) {
- [ ] getPdfViewCtrlTabFragment() != null

2021-08-09 19:11 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +            return mPdfViewCtrlTabHostFragment.getCurrentPdfViewCtrlFragment().isReflowMode();
- [ ] getPdfViewCtrlTabFragment().isReflowMode();

2021-08-09 19:26 UTC, sgong-pdftron approved these changes

2021-08-09 19:37 UTC, merged