Export as Image
PDFTron/pdftron-react-native pull request #331
Opened 2021-07-15 01:07 UTC by dcupidon

Exposed a viewer and a standalone method to convert the pages of a PDF to JPEG, BMP or PNG

2021-08-09 19:10 UTC, sgong-pdftron requested changes

2021-08-09 19:10 UTC, sgong-pdftron commented on API.md
> +Unlike RNPdftron.exportAsImage, this is a viewer method and should only be called *after* a `DocumentView` instance has been created or else unexpected behaviour can occur. This method uses the PDF t
- [ ] after document loaded

2021-08-09 19:10 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/modules/RNPdftronModule.java
> +            String imagePath = ReactUtils.exportAsImageHelper(doc, pageNumber, dpi, exportFormat);
- [ ] read lock on pdfdoc

2021-08-09 19:41 UTC, sgong-pdftron approved these changes

2021-08-18 21:21 UTC, JamesTron requested changes

2021-08-18 21:21 UTC, JamesTron commented on ios/RNPdftron.m
> +        [encoderHints PushBackName:@"JPEG"];
This code seems to be ignoring the requested `exportFormat` and always exporting as JPEG.

2021-08-18 21:21 UTC, JamesTron commented on ios/RNTPTDocumentViewModule.m
> +        NSString *path = [[self documentViewManager] exportAsImageForDocumentViewTag:tag pageNumber:pageNumber dpi:dpi imageFormat:imageFormat];
Everywhere else the param `imageFormat` in this method is referred to as `exportFormat`. Should this one be `exportFormat` too, either for correctness or consistency?

2021-08-19 14:32 UTC, sgong-pdftron approved these changes

2021-09-24 17:48 UTC, JamesTron approved these changes

2021-09-24 22:29 UTC, merged