openThumbnailsView
PDFTron/pdftron-react-native pull request #336
Opened 2021-07-16 00:17 UTC by akwanpdf

Exposed `openThumbnailsView` on iOS and Android.

This method opens a page thumbnails view that allows user to navigate and manipulate document pages.

2021-07-16 17:22 UTC, sgong-pdftron requested changes

2021-07-16 17:22 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +            mPdfViewCtrlTabHostFragment.onPageThumbnailOptionSelected(false, currentPage);
false, null

2021-07-16 17:31 UTC, sgong-pdftron approved these changes

2021-07-19 20:27 UTC, dluco approved these changes

2021-07-20 16:48 UTC, merged