openSearch
PDFTron/pdftron-react-native pull request #338
Opened 2021-07-16 17:42 UTC by akwanpdf

Exposed `openSearch` method.

This method displays a search bar that allows the user to enter and search text within a document.

2021-07-19 20:28 UTC, dluco requested changes

2021-07-19 20:28 UTC, dluco commented on ios/RNTPTDocumentViewModule.m
> +        [[self documentViewManager] openSearchForDocumentViewTag:tag];
Should call `resolve` block here?
```suggestion
        [[self documentViewManager] openSearchForDocumentViewTag:tag];
        resolve(nil);
```

2021-07-20 17:19 UTC, sgong-pdftron approved these changes

2021-08-18 21:15 UTC, JamesTron approved these changes

2021-08-18 21:45 UTC, merged