showViewModeDialog
PDFTron/pdftron-react-native pull request #344
Opened 2021-07-21 23:11 UTC by akwanpdf

Exposed `showViewModeDialog` method for iOS and Android.

This dialog allows users to pick page layout mode, select page color mode, rotate pages, and crop pages.

2021-07-21 23:24 UTC, sgong-pdftron approved these changes

2021-08-18 21:14 UTC, JamesTron requested changes

2021-08-18 21:14 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +{
What happens if you call this method when it's already being presented? I would make this method a no-op if the dialog is already being presented, and document this fact.

```suggestion
{

    if( [self.currentDocumentViewController.settingsViewController isBeingPresented] )
    {
        return;
    }
```

2021-08-18 22:30 UTC, akwanpdf commented
Removing PR as this was already exposed in #305 as `showViewSettings`

2021-08-18 22:30 UTC, closed without merging