[Support] hideSaveCopyOptions
PDFTron/pdftron-react-native pull request #346
Opened 2021-07-26 21:30 UTC by akwanpdf

Add save copy options to `disabledElements` for iOS and Android.

2021-07-26 21:38 UTC, sgong-pdftron requested changes

2021-07-26 21:38 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +            if (!saveCopyOptions.isEmpty()) {
can't really tell from here, but this should be outside of the for loop, is it?

2021-07-26 21:47 UTC, sgong-pdftron approved these changes

2021-07-27 14:48 UTC, sgong-pdftron requested changes
missing API docs

2021-07-27 16:30 UTC, sgong-pdftron approved these changes
forgot that this is for disabledelement....

2021-07-28 17:25 UTC, JamieDass approved these changes

2021-07-28 17:40 UTC, merged