Hide Reply Review State
PDFTron/pdftron-react-native pull request #352
Opened 2021-08-05 17:54 UTC by dcupidon

Implemented prop to hide reply review state in the collaboration viewer.

2021-08-05 17:59 UTC, sgong-pdftron commented on API.md
> +boolean, optional, defaults to false
android only

2021-08-05 19:08 UTC, brandenfung2 requested changes

2021-08-05 19:08 UTC, brandenfung2 commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +            mBuilder = mBuilder.showAnnotationReplyReviewState(!hideReplyReviewState);
Fix spacing

2021-08-05 19:08 UTC, brandenfung2 commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +    public void setHideReplyReviewState(boolean hideReplyReviewState) {
Follow naming convention of other methods. Use `setReplyReviewStateEnabled`. Will also need to update documentation and code below.

2021-08-06 01:07 UTC, brandenfung2 approved these changes

2021-08-06 01:07 UTC, merged