(Support) Excluded Annotation Types
PDFTron/pdftron-react-native pull request #354
Opened 2021-08-06 19:55 UTC by dcupidon

Exposed APIs that excluded specified annotation types from the annotation list

2021-08-06 19:59 UTC, sgong-pdftron requested changes

2021-08-06 19:59 UTC, sgong-pdftron commented on API.md
> +array of string, optional, defaults to none
- [ ] array of `Config.Tools`

2021-08-06 19:59 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
> +        int [] annotTypes = new int [excludedTypes.size()];
- [ ] formatting

2021-08-06 19:59 UTC, sgong-pdftron commented
please update with master

2021-08-06 20:13 UTC, JamesTron requested changes

2021-08-06 20:13 UTC, JamesTron commented on ios/RNTPTDocumentView.h
> +@property (nonatomic, copy, nullable) NSArray<NSString *> *excludedAnnotationListTypes;
```suggestion
@property (nonatomic, strong, nullable) NSArray<NSString *> *excludedAnnotationListTypes;
```
All of the `NSArray<NSString *>` should have a storage type of `strong` not `copy`.

2021-08-06 20:13 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +    _excludedAnnotationListTypes = [excludedAnnotationListTypes copy];
```suggestion
    _excludedAnnotationListTypes = excludedAnnotationListTypes;
```

2021-08-06 20:27 UTC, sgong-pdftron approved these changes

2021-08-09 17:11 UTC, dluco approved these changes

2021-08-09 18:25 UTC, brandenfung2 approved these changes

2021-08-09 18:54 UTC, merged