(Support) onAnnotationsFlattened
PDFTron/pdftron-react-native pull request #407
Opened 2021-10-29 00:17 UTC by dcupidon

Added event listener for when annotations are flattened.

2021-10-29 19:27 UTC, sgong-pdftron approved these changes
version

2021-10-29 21:52 UTC, sgong-pdftron approved these changes

2021-11-05 19:39 UTC, JamesTron requested changes
You can merge without re-review once the read lock is added.

2021-11-05 19:39 UTC, JamesTron commented on ios/RNTPTDocumentView.m
> +    NSString *annotId = [[annot GetUniqueID] IsValid] ? [[annot GetUniqueID] GetAsPDFText] : @"";
Requires a read lock

2021-11-05 23:43 UTC, JamesTron approved these changes

2021-11-05 23:44 UTC, merged