onLoadComplete callback
PDFTron/pdftron-react-native pull request #471
Opened 2022-01-27 22:42 UTC by kmathew-pdftron

onLoadComplete callback Monday

2022-02-01 16:41 UTC, sgong-pdftron requested changes

2022-02-01 16:41 UTC, sgong-pdftron commented on API.md
> +  onDocumentLoaded = {(path) => {
?

2022-02-01 18:51 UTC, kmathew-pdftron commented on API.md
> +  onLoadComplete = {(path) => {
mistake fixed it

2022-02-01 18:51 UTC, kmathew-pdftron commented on API.md
> +  onDocumentLoaded = {(path) => {
mistake fixed

2022-02-03 15:34 UTC, sgong-pdftron approved these changes
no native code, you can merge this one without james

2022-02-03 17:03 UTC, merged