changes in readme
PDFTron/pdftron-react-native pull request #495
Opened 2022-02-14 22:51 UTC by kmathew-pdftron

2022-02-14 23:47 UTC, sgong-pdftron requested changes
add in the first code snippet as usage for integrate with github and second code snippet as usage for npm

2022-02-15 00:36 UTC, sgong-pdftron requested changes

2022-02-15 00:36 UTC, sgong-pdftron commented on README.md
> +  ## Usage-NPM
looks like some strange spacing going on

2022-02-15 01:38 UTC, kmathew-pdftron commented on README.md
> +  ## Usage-NPM
fixed

2022-02-15 15:51 UTC, sgong-pdftron approved these changes

2022-02-15 15:51 UTC, merged