update script to update version after merge
PDFTron/pdftron-react-native pull request #537
Opened 2022-03-30 00:59 UTC by kmathew-pdftron

2022-03-30 14:47 UTC, sgong-pdftron reviewed
code looks fine for me, did you test and see if it works?

2022-03-30 16:06 UTC, kmathew-pdftron commented
yes it works

2022-03-30 17:51 UTC, sgong-pdftron requested changes
I still don't understand how this works, because isn't this going to create 2 separate commit in master? one for the PR, one for the version change? ideally we want 1 commit for both

2022-03-30 17:51 UTC, sgong-pdftron commented on .github/workflows/npm_publish.yml
> +        run: git add  package.json  # <-- Change this to your build path.
there is strange spacing

2022-04-07 16:45 UTC, sgong-pdftron approved these changes

2022-04-07 20:18 UTC, merged