Export as transparent PNG
PDFTron/pdftron-react-native pull request #557
Opened 2022-05-11 17:24 UTC by terryyoon-pdftron

https://linear.app/pdftron/issue/CPM-5/[support-30542]-nitrolabs-export-signature-to-png-transparent

2022-05-11 20:09 UTC, JamesTron requested changes
Looks good, minor detail in documentation, no need to re-review after.

2022-05-11 20:09 UTC, JamesTron commented on API.md
> +transparent | boolean | (only relevant when exported as PNG) whether the background of the image is transparent or opaque white
```suggestion
transparent | boolean | (only relevant when exported as PNG) whether the background of the image is transparent or the color of the PDF page (typically white)
```

2022-05-11 20:10 UTC, sgong-pdftron requested changes

2022-05-11 20:10 UTC, sgong-pdftron commented on src/DocumentView/DocumentView.tsx
> +  exportAsImage = (pageNumber: number, dpi: number, exportFormat: Config.ExportFormat, transparent: boolean): Promise<void | string> => {
this variable needs to be optional otherwise it'd be breaking API

2022-05-11 20:10 UTC, sgong-pdftron commented on index.ts
> +    exportAsImage(pageNumber: number, dpi: number, exportFormat: Config.ExportFormat, filePath: string, transparent: boolean) : Promise<string>;
same here, needs to be optional

2022-05-11 22:22 UTC, sgong-pdftron approved these changes

2022-05-17 17:12 UTC, JamesTron approved these changes

2022-05-17 20:20 UTC, merged