Separate Wonday compatibility APIs CPM-3
PDFTron/pdftron-react-native pull request #563
Opened 2022-05-19 00:22 UTC by terryyoon-pdftron

https://linear.app/pdftron/issue/CPM-3/move-wonday-compatibility-apis-to-be-separate-from-main-apis

2022-06-09 15:54 UTC, sgong-pdftron reviewed
is that it? somehow i feel there should be a lot more, maybe some of them are not mentioned correctly

2022-06-09 16:29 UTC, terryyoon-pdftron commented
this is what i found after searching the API.md file and past PRs for "Wonday", not sure if there is more

2022-06-10 20:39 UTC, sgong-pdftron requested changes
pretty sure one of the `onZoomChanged` or `onScaleChanged` is also wonday related as they are the same, which leads me thinking there are more

2022-06-17 22:21 UTC, JamesTron commented on WondayAPI.md
> +
```suggestion
These APIs are convenience APIs for those migrating from a Wonday implementation.
```

2022-06-17 22:21 UTC, JamesTron approved these changes

2022-08-26 23:06 UTC, closed without merging